name: end_of_term
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - arrow-cpp=21.0.0=hc027f7d_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=h79febb2_1
  - aws-c-common=0.12.4=h79febb2_0
  - aws-c-compression=0.3.1=h79febb2_2
  - aws-c-event-stream=0.5.6=h79febb2_0
  - aws-c-http=0.10.4=h79febb2_0
  - aws-c-io=0.21.4=h79febb2_0
  - aws-c-mqtt=0.13.3=h387b88a_0
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=h79febb2_1
  - aws-checksums=0.2.7=h79febb2_1
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - blas=1.0=openblas
  - brotlicffi=1.2.0.0=py314h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hfe05a68_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.01.04=py314hca03da5_0
  - cffi=2.0.0=py314h73c2a22_1
  - charset-normalizer=3.4.4=py314hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.14.3=py314hd8ed1ab_101
  - debugpy=1.8.20=py314he609de1_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - glog=0.5.0=h313beb8_1
  - icu=73.1=h313beb8_0
  - idna=3.11=py314hca03da5_0
  - ipykernel=7.2.0=pyh5552912_1
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jansson=2.14=h80987f9_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libabseil=20250814.1=cxx17_hbea547f_0
  - libbrotlicommon=1.2.0=hbd7815e_0
  - libbrotlidec=1.2.0=h1e834b2_0
  - libbrotlienc=1.2.0=h5439a07_0
  - libcurl=8.18.0=hd4c70c6_0
  - libcxx=21.1.8=hb4ce287_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.2.0=h09d7db9_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libgrpc=1.74.1=h941cc20_0
  - libiconv=1.18=h92f5915_0
  - libidn2=2.3.8=h9681e36_0
  - libkrb5=1.22.1=ha46c28b_0
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.31=h7813bb4_0
  - libprotobuf=6.33.0=h6acce77_1
  - libre2-11=2025.11.05=hd4f4e8d_0
  - libsodium=1.0.20=h99b78c6_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.22.0=hbe873a3_0
  - libunistring=1.3=h1799b2a_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.8=hfab7639_0
  - lmdb=0.9.31=h79febb2_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.4.2=py314hde9b8b7_0
  - numpy-base=2.4.2=py314hb4b2851_0
  - openssl=3.6.1=hd24854e_1
  - orc=2.2.0=hd6530ca_1
  - packaging=25.0=py314hca03da5_1
  - pandas=3.0.0=py314heb7d0cc_0
  - parso=0.8.6=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=26.0.1=pyhc872135_0
  - platformdirs=4.9.2=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py314ha14b1ff_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py314heb7d0cc_1
  - pycparser=2.23=py314hca03da5_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py314hca03da5_1
  - python=3.14.2=h1858270_101_cp314
  - python-dateutil=2.9.0post0=py314hca03da5_2
  - python-gil=3.14.3=h4df99d1_101
  - python_abi=3.14=2_cp314
  - pyzmq=27.1.0=py312h022ad19_2
  - re2=2025.11.05=h1413154_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py314hca03da5_1
  - setuptools=80.10.2=py314hca03da5_0
  - six=1.17.0=py314hca03da5_0
  - snappy=1.2.2=hc0f95ea_1
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.4=py314h0612a62_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py314hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - wheel=0.46.3=py314hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - warcio==1.7.5
prefix: /Users/carolineroper/opt/anaconda3/envs/end_of_term
